### ISSUE TITLE
stucked at npm start

### ISSUE THREAD

**Issue by wanghaisheng** [atulmy/fullstack-graphql#5]
node version
v5.7.1
npm version
3.6.0
OS
mac 10.12.6 (16G29)
```
➜  webapp git:(master) ✗ npm start            

> webapp@0.1.0 start /Users/wanghaisheng/workspace/fullstack-graphql/webapp
> react-scripts start

/Users/wanghaisheng/workspace/fullstack-graphql/webapp/node_modules/react-scripts/scripts/start.js:31
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/wanghaisheng/.nvm/versions/node/v5.7.1/bin/node" "/Users/wanghaisheng/.nvm/versions/node/v5.7.1/bin/npm" "start"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! webapp@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webapp@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wanghaisheng/workspace/fullstack-graphql/webapp/npm-debug.log

```

**Comment by atulmy** [comment]
Hi @wanghaisheng, issue seems with your Node version. Try upgrading to v6+. You can use `n` (https://github.com/tj/n) to manage your node versions if you want to use more than one version of Node.
